// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Models.Accounts.AccountBalance
{

    public class Money
    {

        [JsonProperty("accruedinterest")]
        public string Accruedinterest { get; set; }

        [JsonProperty("cash")]
        public string Cash { get; set; }

        [JsonProperty("cashavailable")]
        public string Cashavailable { get; set; }

        [JsonProperty("marginbalance")]
        public string Marginbalance { get; set; }

        [JsonProperty("mmf")]
        public string Mmf { get; set; }

        [JsonProperty("total")]
        public string Total { get; set; }

        [JsonProperty("uncleareddeposits")]
        public string Uncleareddeposits { get; set; }

        [JsonProperty("unsettledfunds")]
        public string Unsettledfunds { get; set; }

        [JsonProperty("yield")]
        public string Yield { get; set; }
    }

}
