// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Models.Accounts.AccountBalance
{

    public class Securities
    {

        [JsonProperty("longoptions")]
        public string Longoptions { get; set; }

        [JsonProperty("longstocks")]
        public string Longstocks { get; set; }

        [JsonProperty("options")]
        public string Options { get; set; }

        [JsonProperty("shortoptions")]
        public string Shortoptions { get; set; }

        [JsonProperty("shortstocks")]
        public string Shortstocks { get; set; }

        [JsonProperty("stocks")]
        public string Stocks { get; set; }

        [JsonProperty("total")]
        public string Total { get; set; }
    }

}
