// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKing.API.Accounts.AccountHoldings.Holding;
using Displaydata = TradeKing.API.Accounts.AccountHoldings.Displaydata;

namespace TradeKing.API.Models.Accounts.AccountHoldings
{

    public class Accountholdings
    {

        [JsonProperty("displaydata")]
        public Displaydata Displaydata { get; set; }

        [JsonProperty("holding")]
        public Holding[] Holding { get; set; }

        [JsonProperty("totalsecurities")]
        public string Totalsecurities { get; set; }
    }

}
