// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Accounts.AccountHoldings
{

    public class Displaydata
    {

        [JsonProperty("totalsecurities")]
        public string Totalsecurities { get; set; }
    }

}
