// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKing.API.Base.Responses;
using TradeKing.API.Models.Article;

namespace TradeKing.API.Models.Responses
{
    public class ArticleResponse : BaseResponse
    {
        [JsonProperty("response")]
        public Response Response { get; set; }
    }

}
