// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKing.API.Models.WatchLists;

namespace TradeKing.API.Models.Responses
{

    public class WatchListsResponse
    {

        [JsonProperty("response")]
        public Response Response { get; set; }
    }

}
