// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Accounts.AccountHoldings.Holding
{

    public class Instrument
    {

        [JsonProperty("cusip")]
        public string Cusip { get; set; }

        [JsonProperty("desc")]
        public string Desc { get; set; }

        [JsonProperty("factor")]
        public string Factor { get; set; }

        [JsonProperty("sectyp")]
        public string Sectyp { get; set; }

        [JsonProperty("sym")]
        public string Sym { get; set; }
    }

}
