// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKingAPI.Models.WatchList;

namespace TradeKingAPI.Models.WatchList
{

    public class Response
    {

        [JsonProperty("@id")]
        public string Id { get; set; }

        [JsonProperty("elapsedtime")]
        public string Elapsedtime { get; set; }

        [JsonProperty("watchlists")]
        public Watchlists Watchlists { get; set; }

        [JsonProperty("error")]
        public string Error { get; set; }
    }

}
