// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKingAPI.Models.WatchList;

namespace TradeKingAPI.Models.WatchList
{

    public class Watchlist
    {

        [JsonProperty("watchlistitem")]
        public Watchlistitem[] Watchlistitem { get; set; }
    }

}
