// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKingAPI.Models.WatchList;

namespace TradeKingAPI.Models.WatchList
{
    public class Watchlistitem
    {
        [JsonProperty("costbasis")]
        public string Costbasis { get; set; }

        [JsonProperty("instrument")]
        public Instrument Instrument { get; set; }

        [JsonProperty("qty")]
        public string Qty { get; set; }
    }
}
