// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKingAPI.Models.WatchList;

namespace TradeKingAPI.Models.WatchList
{

    public class Watchlists
    {

        [JsonProperty("watchlist")]
        public Watchlist Watchlist { get; set; }
    }

}
