// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Models.Transactions
{

    public class Security
    {

        [JsonProperty("cusip")]
        public string Cusip { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("sectyp")]
        public string Sectyp { get; set; }

        [JsonProperty("sym")]
        public string Sym { get; set; }
    }

}
