// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Models.Quote
{

    public class Quote
    {

        [JsonProperty("adp_100")]
        public string Adp100 { get; set; }
        public decimal Adp100D { get { return Math.Round(Convert.ToDecimal(Adp100), 2); } }

        [JsonProperty("adp_200")]
        public string Adp200 { get; set; }
        public decimal Adp200D { get { return Math.Round(Convert.ToDecimal(Adp200), 2); } }

        [JsonProperty("adp_50")]
        public string Adp50 { get; set; }
        public decimal Adp50D { get { return Math.Round(Convert.ToDecimal(Adp50), 2); } }

        [JsonProperty("adv_21")]
        public string Adv21 { get; set; }

        [JsonProperty("adv_30")]
        public string Adv30 { get; set; }

        [JsonProperty("adv_90")]
        public string Adv90 { get; set; }

        [JsonProperty("ask")]
        public string Ask { get; set; }
        public decimal AskD { get { return Math.Round(Convert.ToDecimal(Ask), 2); } }

        [JsonProperty("ask_time")]
        public string AskTime { get; set; }

        [JsonProperty("asksz")]
        public string Asksz { get; set; }

        [JsonProperty("basis")]
        public string Basis { get; set; }

        [JsonProperty("beta")]
        public string Beta { get; set; }

        [JsonProperty("bid")]
        public string Bid { get; set; }
        public decimal BidD { get { return Math.Round(Convert.ToDecimal(Bid), 2); } }

        [JsonProperty("bid_time")]
        public string BidTime { get; set; }

        [JsonProperty("bidsz")]
        public string Bidsz { get; set; }

        [JsonProperty("bidtick")]
        public string Bidtick { get; set; }

        [JsonProperty("chg")]
        public string Chg { get; set; }

        [JsonProperty("chg_sign")]
        public string ChgSign { get; set; }

        [JsonProperty("chg_t")]
        public string ChgT { get; set; }

        [JsonProperty("cl")]
        public string Cl { get; set; }

        [JsonProperty("cusip")]
        public string Cusip { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("datetime")]
        public string Datetime { get; set; }

        [JsonProperty("div")]
        public string Div { get; set; }
        public decimal DivD { get { return Math.Round(Convert.ToDecimal(Div), 2); } }

        [JsonProperty("divexdate")]
        public string Divexdate { get; set; }
        public string DivexdateF
        {
            get
            {
                if (Divexdate != null)
                {
                    DateTime d = DateTime.Parse(String.Format("{0}-{1}-{2}", Divexdate.Substring(0, 4), Divexdate.Substring(4, 2), Divexdate.Substring(6, 2)));
                    return String.Format("{0}/{1}/{2}", d.Month, d.Day, d.Year);
                }

                return null;
            }
        }

        [JsonProperty("divfreq")]
        public string Divfreq { get; set; }

        [JsonProperty("divpaydt")]
        public string Divpaydt { get; set; }
        public string DivpaydtF
        {
            get
            {
                DateTime d = DateTime.Parse(String.Format("{0}-{1}-{2}", Divpaydt.Substring(0, 4), Divpaydt.Substring(4, 2), Divpaydt.Substring(6, 2)));
                return String.Format("{0}/{1}/{2}", d.Month, d.Day, d.Year);
            }
        }

        [JsonProperty("dollar_value")]
        public string DollarValue { get; set; }

        [JsonProperty("eps")]
        public string Eps { get; set; }
        public decimal EpsD { get { return Math.Round(Convert.ToDecimal(Eps), 2); } }

        [JsonProperty("exch")]
        public string Exch { get; set; }

        [JsonProperty("exch_desc")]
        public string ExchDesc { get; set; }

        [JsonProperty("hi")]
        public string Hi { get; set; }

        [JsonProperty("iad")]
        public string Iad { get; set; }

        [JsonProperty("incr_vl")]
        public string IncrVl { get; set; }

        [JsonProperty("last")]
        public string Last { get; set;  }
        public decimal LastD { get { return Math.Round(Convert.ToDecimal(Last), 2); } }

        [JsonProperty("lo")]
        public string Lo { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("op_flag")]
        public string OpFlag { get; set; }

        [JsonProperty("opn")]
        public string Opn { get; set; }

        public decimal PayoutRatioD { get
        {
            if (Eps != null)
                return Math.Round(Convert.ToDecimal(Iad)/Convert.ToDecimal(Eps)*100, 2);
            return 0;
        } }

        [JsonProperty("pchg")]
        public string Pchg { get; set; }

        [JsonProperty("pchg_sign")]
        public string PchgSign { get; set; }

        [JsonProperty("pcls")]
        public string Pcls { get; set; }

        [JsonProperty("pe")]
        public string Pe { get; set; }
        public decimal PeD { get { return Math.Round(Convert.ToDecimal(Pe), 2); } }

        [JsonProperty("phi")]
        public string Phi { get; set; }

        [JsonProperty("plo")]
        public string Plo { get; set; }

        [JsonProperty("popn")]
        public string Popn { get; set; }

        [JsonProperty("pr_adp_100")]
        public string PrAdp100 { get; set; }

        [JsonProperty("pr_adp_200")]
        public string PrAdp200 { get; set; }

        [JsonProperty("pr_adp_50")]
        public string PrAdp50 { get; set; }

        [JsonProperty("pr_date")]
        public string PrDate { get; set; }

        [JsonProperty("prbook")]
        public string Prbook { get; set; }
        public decimal PrbookD { get { return Math.Round(Convert.ToDecimal(Prbook), 2); } }

        [JsonProperty("prchg")]
        public string Prchg { get; set; }

        [JsonProperty("pvol")]
        public string Pvol { get; set; }

        [JsonProperty("qcond")]
        public string Qcond { get; set; }

        [JsonProperty("secclass")]
        public string Secclass { get; set; }

        [JsonProperty("sesn")]
        public string Sesn { get; set; }

        [JsonProperty("sesn_vl")]
        public string SesnVl { get; set; }

        [JsonProperty("sho")]
        public string Sho { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("tcond")]
        public string Tcond { get; set; }

        [JsonProperty("timestamp")]
        public string Timestamp { get; set; }

        [JsonProperty("tr_num")]
        public string TrNum { get; set; }

        [JsonProperty("tradetick")]
        public string Tradetick { get; set; }

        [JsonProperty("trend")]
        public string Trend { get; set; }

        [JsonProperty("vl")]
        public string Vl { get; set; }

        [JsonProperty("volatility12")]
        public string Volatility12 { get; set; }

        [JsonProperty("vwap")]
        public string Vwap { get; set; }

        [JsonProperty("wk52hi")]
        public string Wk52hi { get; set; }
        public decimal Wk52hiD { get { return Math.Round(Convert.ToDecimal(Wk52hi), 2); } }

        [JsonProperty("wk52hidate")]
        public string Wk52hidate { get; set; }

        [JsonProperty("wk52lo")]
        public string Wk52lo { get; set; }
        public decimal Wk52loD { get { return Math.Round(Convert.ToDecimal(Wk52lo), 2); } }

        [JsonProperty("wk52lodate")]
        public string Wk52lodate { get; set; }

        [JsonProperty("yield")]
        public string Yield { get; set; }
    }

}
