// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Models.Quote
{

    public class Quotes
    {

        [JsonProperty("quote")]
        public Quote[] Quote { get; set; }
    }

}
