// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKing.API.Models.Responses;

namespace TradeKing.API.Models.WatchLists
{

    public class Watchlist
    {

        [JsonProperty("id")]
        public string Id { get; set; }
    }

}
