// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Transactions
{

    public class Response
    {
        [JsonProperty("@id")]
        public string Id { get; set; }

        [JsonProperty("elapsedtime")]
        public string Elapsedtime { get; set; }

        [JsonProperty("totalrows")]
        public string Totalrows { get; set; }

        [JsonProperty("transactions")]
        public Transactions Transactions { get; set; }
    }

}
