// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Transactions
{

    public class Transactions
    {

        [JsonProperty("transaction")]
        public Transaction[] Transaction { get; set; }
    }

}
