// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Profile
{

    public class Account
    {

        [JsonProperty("account")]
        public string account { get; set; }

        [JsonProperty("fundtrading")]
        public string Fundtrading { get; set; }
        public string FundtradingF { get { return Fundtrading == "true" ? "Yes" : "No"; } }

        [JsonProperty("ira")]
        public string Ira { get; set; }
        public string IraF { get { return Ira == "true" ? "Yes" : "No"; } }

        [JsonProperty("margintrading")]
        public string Margintrading { get; set; }
        public string MargintradingF { get { return Margintrading == "true" ? "Yes" : "No"; } }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("optionlevel")]
        public string Optionlevel { get; set; }

        [JsonProperty("shared")]
        public string Shared { get; set; }
        public string SharedF { get { return Shared == "true" ? "Yes" : "No"; } }

        [JsonProperty("stocktrading")]
        public string Stocktrading { get; set; }
        public string StocktradingF { get { return Stocktrading == "true" ? "Yes" : "No"; } }
    }

}
