// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Profile
{

    public class Userdata
    {

        [JsonProperty("account")]
        public Account Account { get; set; }

        [JsonProperty("disabled")]
        public string Disabled { get; set; }
        public string DisabledF { get { return Disabled == "true" ? "Yes" : "No"; } }

        [JsonProperty("resetpassword")]
        public string Resetpassword { get; set; }
        public string ResetpasswordF { get { return Resetpassword == "true" ? "Yes" : "No"; } }

        [JsonProperty("resettradingpassword")]
        public string Resettradingpassword { get; set; }
        public string ResettradingpasswordF { get { return Resettradingpassword == "true" ? "Yes" : "No"; } }

        [JsonProperty("userprofile")]
        public Userprofile Userprofile { get; set; }
    }

}
