// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Profile
{

    public class Userprofile
    {

        [JsonProperty("entry")]
        public Entry[] Entry { get; set; }

        public string LastLoginType { get { return Entry.Length > 2 ? Entry[2].Value : String.Empty; } }
        public string NewMsg
        {
            get
            {
                if (Entry.Length > 3)
                {
                    return Entry[3].Value.ToLower() == "y" ? "Yes" : "No";
                }
                return "?";
            }
        }

    }

}
