// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Accounts.AccountHoldings.Holding
{

    public class Displaydata
    {

        [JsonProperty("accounttype")]
        public string Accounttype { get; set; }

        [JsonProperty("assetclass")]
        public string Assetclass { get; set; }

        [JsonProperty("change")]
        public string Change { get; set; }

        [JsonProperty("costbasis")]
        public string Costbasis { get; set; }

        [JsonProperty("desc")]
        public string Desc { get; set; }

        [JsonProperty("lastprice")]
        public string Lastprice { get; set; }

        [JsonProperty("marketvalue")]
        public string Marketvalue { get; set; }

        [JsonProperty("marketvaluechange")]
        public string Marketvaluechange { get; set; }

        [JsonProperty("qty")]
        public string Qty { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }
    }

}
