// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Accounts.AccountHoldings.Holding
{

    public class Holding
    {

        [JsonProperty("accounttype")]
        public string Accounttype { get; set; }

        [JsonProperty("costbasis")]
        public string Costbasis { get; set; }

        [JsonProperty("displaydata")]
        public Displaydata Displaydata { get; set; }

        [JsonProperty("gainloss")]
        public string Gainloss { get; set; }
        public decimal GainlossD { get { return Math.Round(Convert.ToDecimal(Gainloss), 2); } }

        [JsonProperty("instrument")]
        public Instrument Instrument { get; set; }

        [JsonProperty("marketvalue")]
        public string Marketvalue { get; set; }
        public decimal MarketvalueD { get { return Math.Round(Convert.ToDecimal(Marketvalue), 2); } }

        [JsonProperty("marketvaluechange")]
        public string Marketvaluechange { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }
        public decimal PriceD { get { return Math.Round(Convert.ToDecimal(Price), 2); } }

        [JsonProperty("purchaseprice")]
        public string Purchaseprice { get; set; }

        [JsonProperty("qty")]
        public string Qty { get; set; }

        [JsonProperty("quote")]
        public Quote Quote { get; set; }

        [JsonProperty("sodcostbasis")]
        public string Sodcostbasis { get; set; }

        [JsonProperty("underlying")]
        public object Underlying { get; set; }
    }

}
