// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Accounts.AccountHoldings.Holding
{

    public class Quote
    {

        [JsonProperty("change")]
        public string Change { get; set; }

        [JsonProperty("extendedquote")]
        public Extendedquote Extendedquote { get; set; }

        [JsonProperty("format")]
        public object Format { get; set; }

        [JsonProperty("lastprice")]
        public string Lastprice { get; set; }
    }

}
