// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Quote
{

    public class Response
    {

        [JsonProperty("@id")]
        public string Id { get; set; }

        [JsonProperty("quotes")]
        public Quotes Quotes { get; set; }
    }

}
