// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKing.API.Models.Streaming
{

    public class Quote : StreamDataItem
    {

        [JsonProperty("ask")]
        public string Ask { get; set; }

        [JsonProperty("asksz")]
        public string Asksz { get; set; }

        [JsonProperty("bid")]
        public string Bid { get; set; }

        [JsonProperty("bidsz")]
        public string Bidsz { get; set; }

        [JsonProperty("qcond")]
        public string Qcond { get; set; }

       
    }

}
