// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Article
{
    public class Article
    {
        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("headline")]
        public string Headline { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("story")]
        public object Story { get; set; }
    }

}
