// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Article
{
    public class Articles
    {
        [JsonProperty("article")]
        public Article[] Article { get; set; }
    }

}
