// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TradeKingAPI.Models.Accounts.AccountBalance
{

    public class Accountbalance
    {

        [JsonProperty("account")]
        public string Account { get; set; }

        [JsonProperty("accountvalue")]
        public string Accountvalue { get; set; }

        [JsonProperty("backofficehouseexcess")]
        public string Backofficehouseexcess { get; set; }

        [JsonProperty("fedcall")]
        public string Fedcall { get; set; }

        [JsonProperty("housecall")]
        public string Housecall { get; set; }

        [JsonProperty("maintenanceexcess")]
        public string Maintenanceexcess { get; set; }

        [JsonProperty("money")]
        public Money Money { get; set; }

        [JsonProperty("securities")]
        public Securities Securities { get; set; }
    }

}
