// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TradeKingAPI.Base.Responses;
using TradeKingAPI.Models.Profile;

namespace TradeKingAPI.Models.Responses
{

    public class ProfileResponse : BaseResponse
    {

        [JsonProperty("response")]
        public Response Response { get; set; }
    }

}
